hosts: [
  { host_ip: "192.168.57.48", host_name: "harbor-registry"}
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" },
  ]
